CREATE USER EMBULK IDENTIFIED BY "embulk_pw";
GRANT DBA TO EMBULK;

CREATE TABLE TEST1 (
    ID              CHAR(4),
    VARCHAR2_ITEM   VARCHAR2(20),
    NUMBER_ITEM     NUMBER(10,2),
    DATE_ITEM       DATE,
    TIMESTAMP_ITEM  TIMESTAMP,
    PRIMARY KEY (ID)
);
